/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NosRealisationsRouteImport } from './routes/nos-realisations'
import { Route as NosReferencesRouteImport } from './routes/nos-references'
import { Route as NosServicesRouteImport } from './routes/nos-services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NosRealisationsRoute = NosRealisationsRouteImport.update({
  id: '/nos-realisations',
  path: '/nos-realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const NosReferencesRoute = NosReferencesRouteImport.update({
  id: '/nos-references',
  path: '/nos-references',
  getParentRoute: () => rootRouteImport,
} as any)
const NosServicesRoute = NosServicesRouteImport.update({
  id: '/nos-services',
  path: '/nos-services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/nos-realisations': typeof NosRealisationsRoute
  '/nos-references': typeof NosReferencesRoute
  '/nos-services': typeof NosServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/nos-realisations': typeof NosRealisationsRoute
  '/nos-references': typeof NosReferencesRoute
  '/nos-services': typeof NosServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/nos-realisations': typeof NosRealisationsRoute
  '/nos-references': typeof NosReferencesRoute
  '/nos-services': typeof NosServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/nos-realisations'
    | '/nos-references'
    | '/nos-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/nos-realisations'
    | '/nos-references'
    | '/nos-services'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/nos-realisations'
    | '/nos-references'
    | '/nos-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  NosRealisationsRoute: typeof NosRealisationsRoute
  NosReferencesRoute: typeof NosReferencesRoute
  NosServicesRoute: typeof NosServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-realisations': {
      id: '/nos-realisations'
      path: '/nos-realisations'
      fullPath: '/nos-realisations'
      preLoaderRoute: typeof NosRealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-references': {
      id: '/nos-references'
      path: '/nos-references'
      fullPath: '/nos-references'
      preLoaderRoute: typeof NosReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-services': {
      id: '/nos-services'
      path: '/nos-services'
      fullPath: '/nos-services'
      preLoaderRoute: typeof NosServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  NosRealisationsRoute: NosRealisationsRoute,
  NosReferencesRoute: NosReferencesRoute,
  NosServicesRoute: NosServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
